# This workflow checks that the code in the repo is formatted according to the
# Google Java Style Guide

name: Code Formatting Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
        cache: 'gradle'
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    # The google formatter is broken atm. Disabling for now.
    - name: Verify all Java files are formatted correctly according to the Google Java Style Guide using Gradle
      uses: gradle/gradle-build-action@v2
      if: ${{ false }}
      id: verifygooglejavaformat
      with:
        gradle-version: wrapper
        arguments: verifyGoogleJavaFormat
    - name: Create summary if format check failed
      if: ${{ false }}
      # Enable this when Google Java formatter is enabled
      # if: ${{ steps.verifygooglejavaformat.outcome == 'failure' }}
      run: |
        echo "Run the command `./gradlew goJF` to fix Java formatting." >> $GITHUB_STEP_SUMMARY
